//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQPractice01.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStudent
    {
        public int StudentId { get; set; }
        public string StdName { get; set; }
        public double Stdcgpa { get; set; }
        public int StdSem { get; set; }
        public string ProfId { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
